#%RAML 1.0
title: My API with Types
baseUri: https://domain.com
mediaType: [application/json, application/xml]
protocols: [HTTP, HTTPS]

description: |
  ## This is test API
  Hello tests

/test1:
  /subsesource:
/test2:
